aerial_robot_control_name: aerial_robot_control/spidar_walk

controller:

  control_verbose: false

  walk:
    joint_ctrl_rate: 10.0 # 10 Hz
    servo_angle_bias: 0 # rad
    servo_angle_bias_torque: 4 # Nm
    servo_max_torque: 6.5 # Nm

    thrust_force_weight: 1.0
    joint_torque_weight: 0.0 # 0.1 # 10.0 ~ 20.0

    joint_static_torque_limit: 3.0
    raise_joint_static_torque_limit: 1.5 # < joint_static_torque_limit
    pedipulate_joint_static_torque_limit: 1.0

    contact_leg_force_i_gain: 1.0 # /s

    check_interval: 0.1


    xy:
      p_gain: 100.0 # N/m:
      i_gain: 0.0 #
      d_gain: 0.0
      limit_sum: 10.0
      limit_p: 10.0
      limit_i: 0.0
      limit_d: 0.0

    z:
      p_gain: 100.0 # N/m: 2N/0.01m
      i_gain: 0.0 # 20.0 N/m
      d_gain: 0.0
      limit_sum: 20.0
      limit_p: 20.0
      limit_i: 20.0
      limit_d: 20.0
      offset: 2.0

    rot:
      p_gain: 0        

    joint:
      joint_error_angle_thresh: 0.02 # rad

      p_gain: 0.0 # Nm/rad; 20: 0.1 rad -> 2 Nm
      i_gain: 0.0
      limit_sum: 0.0
      limit_p: 0.0
      limit_i: 0.0
      limit_d: 0.0
