zeros:
  joint1_pitch: -0.5
  joint1_yaw: 1.0 # 0.785
  joint2_pitch: -0.3
  joint2_yaw: 1.2 # 0.785
  joint3_pitch: -0.3
  joint3_yaw: 1.0 # 0.785
  joint4_pitch: -0.3
  joint4_yaw: 1.0 # 0.785
  joint5_pitch: -0.3
  joint5_yaw: 1.1 # 0.785
  joint6_pitch: -0.3
  joint6_yaw: 1.2 # 0.785
  joint7_pitch: -0.3
  joint7_yaw: 1.2 # 0.785
  gimbal1_pitch: -0.3
  gimbal2_roll: 0.1
  gimbal4_roll: 0.4
  gimbal4_pitch: -0.3
  gimbal6_roll: -0.1
  gimbal6_pitch: -0.2
  gimbal8_roll: 0.26